const fs = require('fs');
const path = 'src/i18n/translations.ts';
let content = fs.readFileSync(path, 'utf8');

const marker = "const zh: Dict = {\n";
const count = content.split(marker).length - 1;
if (count !== 1) {
  console.error(`ABORT: marker found ${count} times (expected 1).`);
  process.exit(1);
}

const entries = [
  ["aiChat.emptyState", "开始与KHOEM-AI对话"],
  ["aiChat.placeholder", "输入命令或问题…"],
  ["aiChat.subtitle", "您的助手"],
  ["intl.pin", "固定{name}"],
  ["intl.unpin", "取消固定{name}"],
  ["navgroup.overview", "概览"],
  ["navgroup.devicesControl", "设备与控制"],
  ["navgroup.securitySafety", "安全与保护"],
  ["navgroup.organization", "组织"],
  ["view.dashboard.subtitle", "KSV全车队的实时概览"],
  ["view.devices.subtitle", "管理所有已连接的设备"],
  ["view.controls.subtitle", "发送并查看设备命令"],
  ["view.protocols.subtitle", "连接状态与协议健康度"],
  ["view.gateway.subtitle", "边缘网关与离线模式"],
  ["view.security.subtitle", "身份、会话与访问权限"],
  ["view.safety.subtitle", "安全规则与联锁"],
  ["view.organization.subtitle", "站点、团队与角色"],
  ["view.international.subtitle", "国家、语言与时区"],
  ["view.audit.subtitle", "完整的活动与安全日志"],
  ["view.certificates.subtitle", "培训与合规记录"],
  ["view.settings.subtitle", "账户与平台偏好设置"],
  ["dashboard.trend.devicesUp", "2.4%"],
  ["dashboard.trend.rulesNew", "新增12条"],
  ["dashboard.trend.gatewayOffline", "离线1个"],
  ["dashboard.trend.countriesAdded", "新增3个"],
  ["dashboard.traffic.title", "平台流量"],
  ["dashboard.traffic.subtitle", "每分钟命令消息数 — 过去24小时"],
  ["dashboard.traffic.live", "实时"],
  ["dashboard.traffic.peakThroughput", "峰值吞吐量"],
  ["dashboard.traffic.cmdPerMin", "{count} 条/分钟"],
  ["dashboard.traffic.avgLatency", "平均延迟"],
  ["dashboard.traffic.ms", "{count} 毫秒"],
  ["dashboard.traffic.uptime", "正常运行时间"],
  ["dashboard.traffic.days", "{count} 天"],
  ["dashboard.health.title", "设备健康状况"],
  ["dashboard.health.subtitle", "全球车队状态"],
  ["dashboard.health.online", "在线"],
  ["dashboard.health.warning", "警告"],
  ["dashboard.health.offline", "离线"],
  ["dashboard.alerts.title", "告警活动"],
  ["dashboard.alerts.subtitle", "安全与保护触发事件"],
  ["dashboard.alerts.openAlerts", "未处理告警"],
  ["dashboard.alerts.critical", "严重{count}条"],
  ["dashboard.sites.title", "站点负载"],
  ["dashboard.sites.subtitle", "各站点设备数量与网关利用率"],
  ["dashboard.sites.viewAll", "查看全部"],
  ["dashboard.sites.devicesAndLoad", "{count} 台设备 · {load}%"],
  ["dashboard.recentDevices.title", "最近设备"],
  ["dashboard.safetyRules.title", "安全规则"],
  ["dashboard.safetyRules.triggered", "{scope} · 已触发{count}次"],
  ["dashboard.protocols.title", "协议健康状况"],
  ["dashboard.protocols.devicesAndLatency", "{count} 台设备 · {latency}毫秒"],
  ["dashboard.gateway.title", "边缘网关车队"],
  ["dashboard.gateway.subtitle", "具备离线模式能力的本地控制器"],
  ["dashboard.gateway.onlineBadge", "{online}/{total} 在线"],
  ["dashboard.gateway.cpu", "CPU"],
  ["dashboard.gateway.mem", "内存"],
  ["dashboard.gateway.devices", "设备"],
  ["view.devices.registryTitle", "设备注册表"],
  ["view.devices.acrossAllSites", "覆盖所有站点的设备"],
  ["view.devices.export", "导出"],
  ["view.devices.searchPlaceholder", "按名称或设备ID搜索…"],
  ["view.devices.noMatch", "没有符合筛选条件的设备。"],
  ["view.devices.filter.all", "全部"],
  ["view.devices.filter.online", "在线"],
  ["view.devices.filter.warning", "警告"],
  ["view.devices.filter.maintenance", "维护中"],
  ["view.devices.filter.offline", "离线"],
  ["view.devices.status.online", "在线"],
  ["view.devices.status.warning", "警告"],
  ["view.devices.status.offline", "离线"],
  ["view.devices.status.maintenance", "维护中"],
  ["view.devices.category.access", "门禁"],
  ["view.devices.category.climate", "空调"],
  ["view.devices.category.industrial", "工业"],
  ["view.devices.category.vehicle", "车辆"],
  ["view.devices.category.sensor", "传感器"],
  ["view.devices.category.network", "网络"],
  ["view.devices.table.device", "设备"],
  ["view.devices.table.category", "类别"],
  ["view.devices.table.protocol", "协议"],
  ["view.devices.table.location", "位置"],
  ["view.devices.table.signal", "信号强度"],
  ["view.devices.table.firmware", "固件"],
  ["view.devices.table.status", "状态"],
  ["view.audit.title", "不可篡改的审计追踪"],
  ["view.audit.subtitleText", "加密链式事件日志 — 全平台活动"],
  ["view.audit.chainVerified", "链已验证"],
  ["view.audit.searchPlaceholder", "按操作者、操作或目标搜索…"],
  ["view.audit.noMatch", "没有符合筛选条件的事件。"],
  ["view.audit.loading", "正在加载审计追踪…"],
  ["view.audit.loadFailed", "无法加载审计追踪。"],
  ["view.audit.category.all", "全部"],
  ["view.audit.category.auth", "认证"],
  ["view.audit.category.device", "设备"],
  ["view.audit.category.safety", "安全"],
  ["view.audit.category.admin", "管理"],
  ["view.audit.category.network", "网络"],
  ["view.audit.result.success", "成功"],
  ["view.audit.result.denied", "拒绝"],
  ["view.audit.result.error", "错误"],
  ["view.certificates.heading", "Sololearn认证证书"],
  ["view.certificates.description", "KSV团队成员持有的已验证专业认证"],
  ["view.certificates.certificatesLabel", "证书"],
  ["view.certificates.verifiedLabel", "已验证"],
  ["view.certificates.verified", "已验证"],
  ["view.certificates.issued", "颁发日期"],
  ["view.certificates.expires", "有效期至"],
  ["view.certificates.viewCertificate", "查看证书"],
  ["view.certificates.category.development", "开发"],
  ["view.certificates.category.security", "安全"],
  ["view.certificates.category.iot", "物联网"],
  ["view.certificates.category.database", "数据库"],
  ["view.certificates.category.cloud", "云计算"],
  ["view.controls.vaultDoor.name", "北金库门"],
  ["view.controls.vaultDoor.site", "法兰克福总部"],
  ["view.controls.hvac.name", "洁净室空调"],
  ["view.controls.hvac.site", "台北工厂"],
  ["view.controls.pressEstop.name", "冲压线7号紧急停止"],
  ["view.controls.pressEstop.site", "斯图加特工厂"],
  ["view.controls.robotArm.name", "机械臂 RA-04"],
  ["view.controls.robotArm.site", "大阪工厂"],
  ["view.controls.eastGate.name", "东门道闸"],
  ["view.controls.eastGate.site", "迪拜物流中心"],
  ["view.controls.coldStorage.name", "冷库监控"],
  ["view.controls.coldStorage.site", "鹿特丹港"],
  ["view.controls.secured", "已锁定"],
  ["view.controls.unlocked", "已解锁"],
  ["view.controls.unlock", "解锁"],
  ["view.controls.lock", "锁定"],
  ["view.controls.setpoint", "设定温度"],
  ["view.controls.fan", "风扇"],
  ["view.controls.mode", "模式"],
  ["view.controls.cool", "制冷"],
  ["view.controls.filter", "滤网"],
  ["view.controls.estop", "紧急停止"],
  ["view.controls.lineHalted", "产线已停止"],
  ["view.controls.pressOperational", "冲压机运行中"],
  ["view.controls.reset", "重置"],
  ["view.controls.speedLimit", "速度限制"],
  ["view.controls.humanZoneOverride", "人员区域覆盖"],
  ["view.controls.active", "已启用"],
  ["view.controls.collisionDetection", "碰撞检测"],
  ["view.controls.enabled", "已启用"],
  ["view.controls.maintenance", "维护中"],
  ["view.controls.barrierOpen", "道闸已开启"],
  ["view.controls.barrierClosed", "道闸已关闭"],
  ["view.controls.close", "关闭"],
  ["view.controls.open", "开启"],
  ["view.controls.targetTemp", "目标温度"],
  ["view.controls.current", "当前值"],
  ["view.controls.logTitle", "实时控制活动"],
  ["view.controls.logSubtitle", "过去一小时内发送的命令"],
  ["view.controls.logLoading", "正在加载最近活动…"],
  ["view.controls.logEmpty", "尚未发送任何命令。"],
  ["view.controls.logLoadFailed", "无法加载最近活动。"],
  ["view.controls.log.vaultDoor", "北金库门"],
  ["view.controls.log.robotArm", "机械臂 RA-04"],
  ["view.controls.log.hvac", "洁净室空调"],
  ["view.controls.log.pressLine", "冲压线7号"],
  ["view.controls.log.eastGate", "东门道闸"],
  ["view.gateway.online", "在线"],
  ["view.gateway.degraded", "性能下降"],
  ["view.gateway.offline", "离线"],
  ["view.gateway.memory", "内存"],
  ["view.gateway.firmware", "固件"],
  ["view.gateway.lastSync", "最后同步"],
  ["view.gateway.offlineMode", "离线模式"],
  ["view.gateway.connected", "已连接"],
  ["view.gateway.reconnecting", "正在重新连接"],
  ["view.gateway.discoveryTitle", "本地网络发现"],
  ["view.gateway.discoverySubtitle", "面向边缘设备的mDNS / UDP广播扫描"],
  ["view.gateway.discovery.frankfurt", "法兰克福边缘控制器"],
  ["view.gateway.discovery.badgeReader", "门禁读卡器 B2-A"],
  ["view.gateway.discovery.singapore", "新加坡边缘控制器"],
  ["view.gateway.discovery.airSensor", "屋顶空气传感器"],
  ["view.organization.hierarchyTitle", "组织架构"],
  ["view.organization.hierarchySubtitle", "公司 → 站点 → 楼宇 → 设备的策略继承"],
  ["view.organization.nodes", "节点"],
  ["view.organization.users", "用户"],
  ["view.organization.rules", "规则"],
  ["view.organization.accessPoliciesTitle", "访问策略"],
  ["view.organization.accessPoliciesSubtitle", "基于策略的访问控制（PBAC）规则"],
  ["view.organization.roleDefinitionsTitle", "角色定义"],
  ["view.organization.roleDefinitionsSubtitle", "平台级角色目录"],
  ["view.organization.type.company", "控股公司"],
  ["view.organization.type.site", "区域/站点"],
  ["view.organization.type.building", "楼宇"],
  ["view.organization.type.floor", "楼层"],
  ["view.organization.site.frankfurt", "法兰克福总部"],
  ["view.organization.site.singapore", "新加坡数据中心"],
  ["view.organization.site.taipei", "台北工厂"],
  ["view.organization.site.emea", "欧非中东地区"],
  ["view.organization.site.apac", "亚太地区"],
  ["view.organization.policy.hqStrict", "总部严格策略"],
  ["view.organization.policy.dcCritical", "数据中心关键策略"],
  ["view.organization.policy.fabCleanroom", "工厂洁净室策略"],
  ["view.organization.policy.emeaBaseline", "欧非中东基准策略"],
  ["view.organization.policy.apacBaseline", "亚太基准策略"],
  ["view.organization.role.orgOwner", "组织所有者"],
  ["view.organization.role.siteAdmin", "站点管理员"],
  ["view.organization.role.safetyEngineer", "安全工程师"],
  ["view.organization.role.networkAdmin", "网络管理员"],
  ["view.organization.role.operator", "操作员"],
  ["view.organization.role.viewer", "只读用户"],
  ["view.organization.perms.orgOwner", "完全平台控制权限"],
  ["view.organization.perms.siteAdmin", "站点级管理权限"],
  ["view.organization.perms.safetyEngineer", "安全规则与设备控制权限"],
  ["view.organization.perms.networkAdmin", "网关与协议配置权限"],
  ["view.organization.perms.operator", "设备控制与审计查看权限"],
  ["view.organization.perms.viewer", "仅限查看仪表板"],
  ["view.protocols.abstractionTitle", "协议抽象层"],
  ["view.protocols.abstractionSubtitle", "覆盖所有传输协议的统一适配器接口"],
  ["view.protocols.latency", "延迟"],
  ["view.protocols.encryptionTitle", "加密标准"],
  ["view.protocols.capabilityRegistryTitle", "能力注册表"],
  ["view.protocols.dev", "台"],
  ["view.protocols.status.active", "运行中"],
  ["view.protocols.status.degraded", "性能下降"],
  ["view.protocols.status.offline", "离线"],
  ["view.protocols.enc.tls", "TLS 1.3"],
  ["view.protocols.enc.wpa3", "WPA3企业版"],
  ["view.protocols.enc.aesBle", "AES-CCM（蓝牙BLE）"],
  ["view.protocols.enc.aesZigbee", "AES-128（Zigbee）"],
  ["view.safety.stat.rulesActive", "已启用规则"],
  ["view.safety.stat.totalTriggers", "总触发次数（30天）"],
  ["view.safety.stat.criticalRules", "严重规则"],
  ["view.safety.scope.all", "所有范围"],
  ["view.safety.scope.door", "门禁"],
  ["view.safety.scope.vehicle", "车辆"],
  ["view.safety.scope.industrial", "工业"],
  ["view.safety.condition", "条件"],
  ["view.safety.action", "操作"],
  ["view.safety.triggered", "已触发{count}次"],
  ["view.safety.active", "已启用"],
  ["view.safety.disabled", "已禁用"],
  ["view.safety.severity.critical", "严重"],
  ["view.safety.severity.high", "高"],
  ["view.safety.severity.medium", "中"],
  ["view.safety.severity.low", "低"],
  ["view.security.stat.grade", "安全等级"],
  ["view.security.stat.activeSessions", "活跃会话"],
  ["view.security.stat.mfaCoverage", "多因素认证覆盖率"],
  ["view.security.stat.deniedAttempts", "拒绝尝试次数（24小时）"],
  ["view.security.sessions.title", "活跃会话"],
  ["view.security.sessions.subtitle", "平台上已认证的用户会话"],
  ["view.security.table.user", "用户"],
  ["view.security.table.method", "方式"],
  ["view.security.table.location", "位置"],
  ["view.security.table.mfa", "多因素认证"],
  ["view.security.table.lastActive", "最后活跃"],
  ["view.security.table.status", "状态"],
  ["view.security.mfa.on", "开启"],
  ["view.security.mfa.off", "关闭"],
  ["view.security.authMethods.title", "认证方式"],
  ["view.security.authMethods.sessions", "个会话"],
  ["view.security.policies.title", "安全策略"],
  ["view.security.policy.zeroPlaintext", "密码零明文存储策略"],
  ["view.security.policy.oauthOidc", "OAuth 2.0 / OIDC流程"],
  ["view.security.policy.otpRecovery", "OTP恢复备份"],
  ["view.security.policy.sessionAudit", "会话审计日志"],
  ["view.security.policy.forceMfaAdmins", "强制管理员启用多因素认证"],
  ["view.security.policy.ipAllowlist", "IP白名单（生产环境）"],
  ["view.security.status.enforced", "已强制执行"],
  ["view.security.status.partial", "部分执行"],
  ["view.settings.platform.title", "平台"],
  ["view.settings.platform.subtitle", "核心平台行为"],
  ["view.settings.autoUpdate.label", "自动固件更新"],
  ["view.settings.autoUpdate.desc", "向符合条件的设备推送OTA更新"],
  ["view.settings.offlineMode.label", "边缘离线模式"],
  ["view.settings.offlineMode.desc", "允许网关在无云端连接时运行"],
  ["view.settings.auditLog.label", "不可篡改的审计日志"],
  ["view.settings.auditLog.desc", "对所有事件进行加密链式记录"],
  ["view.settings.security.title", "安全"],
  ["view.settings.security.subtitle", "身份验证与访问策略"],
  ["view.settings.twoFactor.label", "要求所有管理员启用双因素认证"],
  ["view.settings.twoFactor.desc", "对管理员和操作员角色强制启用多因素认证"],
  ["view.settings.zeroPlaintext.label", "密码零明文存储策略"],
  ["view.settings.zeroPlaintext.desc", "采用Argon2id哈希算法，不存储明文"],
  ["view.settings.safetyOverride.label", "允许覆盖安全规则"],
  ["view.settings.safetyOverride.desc", "允许工程师临时禁用规则"],
  ["view.settings.notifications.title", "通知"],
  ["view.settings.notifications.subtitle", "告警推送渠道"],
  ["view.settings.emailAlerts.label", "邮件告警"],
  ["view.settings.emailAlerts.desc", "将严重告警发送至管理员邮箱"],
  ["view.settings.smsAlerts.label", "短信告警"],
  ["view.settings.smsAlerts.desc", "通过短信网关发送严重告警"],
  ["view.settings.localization.title", "本地化与数据"],
  ["view.settings.localization.subtitle", "语言与存储偏好设置"],
  ["view.settings.defaultLanguage", "默认语言"],
  ["view.settings.defaultTimezone", "默认时区"],
  ["view.settings.timezoneAuto", "自动（从浏览器检测）"],
  ["view.settings.databaseBackup", "数据库备份"],
  ["view.settings.backupInterval", "自动 · 每{hours}小时一次"],
  ["view.settings.saveBar.note", "更改将应用于所有站点和网关。"],
  ["view.settings.saveBar.save", "保存更改"],
];

let block = "";
for (const [key, val] of entries) {
  const escaped = val.replace(/'/g, "\\'");
  block += `  '${key}': '${escaped}',\n`;
}

content = content.replace(marker, marker + block);
fs.writeFileSync(path, content, 'utf8');
console.log(`Done. Inserted ${entries.length} keys into zh.`);
